package cn.edu.pojo;

import java.util.Date;

public class Course {

    @Override
    public String toString() {
        return "Course{" +
              "courseid=" + courseid +
              ", coursename='" + coursename + '\'' +
              ", coursetype='" + coursetype + '\'' +
              ", addtime=" + addtime +
              ", sourceprice=" + sourceprice +
              ", currentprice=" + currentprice +
              ", title='" + title + '\'' +
              ", context='" + context + '\'' +
              ", lessionnum=" + lessionnum +
              ", logo='" + logo + '\'' +
              ", updatetime=" + updatetime +
              ", pagebuycount=" + pagebuycount +
              ", pageviewcount=" + pageviewcount +
              '}';
    }

    /**
     * 主键，id
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer courseid;

    /**
     *  课程名
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String coursename;

    /**
     *  课程的类别
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String coursetype;

    /**
     *
     *  增加课程的时间
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Date addtime;

    /**
     *
     *      原价
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Double sourceprice;

    /**
     *
     *  优惠后价格
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Double currentprice;

    /**
     *
     *  课程主题介绍
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String title;

    /**
     *  课程主题详情
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String context;

    /**
     *  总课时
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer lessionnum;

    /**
     *  图片路径
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String logo;

    /**
     *
     *  修改课程的时间
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Date updatetime;

    /**
     *
     *  总销量
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer pagebuycount;

    /**
     *  浏览人数
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer pageviewcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseId
     *
     * @return the value of course.courseId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseId
     *
     * @param courseid the value for course.courseId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseName
     *
     * @return the value of course.courseName
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseName
     *
     * @param coursename the value for course.courseName
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseType
     *
     * @return the value of course.courseType
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getCoursetype() {
        return coursetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseType
     *
     * @param coursetype the value for course.courseType
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setCoursetype(String coursetype) {
        this.coursetype = coursetype == null ? null : coursetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.addTime
     *
     * @return the value of course.addTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.addTime
     *
     * @param addtime the value for course.addTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sourcePrice
     *
     * @return the value of course.sourcePrice
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Double getSourceprice() {
        return sourceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sourcePrice
     *
     * @param sourceprice the value for course.sourcePrice
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setSourceprice(Double sourceprice) {
        this.sourceprice = sourceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.currentPrice
     *
     * @return the value of course.currentPrice
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Double getCurrentprice() {
        return currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.currentPrice
     *
     * @param currentprice the value for course.currentPrice
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setCurrentprice(Double currentprice) {
        this.currentprice = currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.title
     *
     * @return the value of course.title
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.title
     *
     * @param title the value for course.title
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.context
     *
     * @return the value of course.context
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.context
     *
     * @param context the value for course.context
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.lessionNum
     *
     * @return the value of course.lessionNum
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getLessionnum() {
        return lessionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.lessionNum
     *
     * @param lessionnum the value for course.lessionNum
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setLessionnum(Integer lessionnum) {
        this.lessionnum = lessionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.logo
     *
     * @return the value of course.logo
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.logo
     *
     * @param logo the value for course.logo
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.updateTime
     *
     * @return the value of course.updateTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.updateTime
     *
     * @param updatetime the value for course.updateTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.pageBuyCount
     *
     * @return the value of course.pageBuyCount
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getPagebuycount() {
        return pagebuycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.pageBuyCount
     *
     * @param pagebuycount the value for course.pageBuyCount
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setPagebuycount(Integer pagebuycount) {
        this.pagebuycount = pagebuycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.pageViewCount
     *
     * @return the value of course.pageViewCount
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getPageviewcount() {
        return pageviewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.pageViewCount
     *
     * @param pageviewcount the value for course.pageViewCount
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setPageviewcount(Integer pageviewcount) {
        this.pageviewcount = pageviewcount;
    }
}