package cn.edu.pojo;

import java.util.Date;

public class Kpoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.kpointId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer kpointid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.courseId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.name
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.addTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.playCount
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer playcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.videoUrl
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String videourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.teachearId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Integer teachearid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.playTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private Date playtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpoint.countent
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    private String countent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.kpointId
     *
     * @return the value of kpoint.kpointId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getKpointid() {
        return kpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.kpointId
     *
     * @param kpointid the value for kpoint.kpointId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setKpointid(Integer kpointid) {
        this.kpointid = kpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.courseId
     *
     * @return the value of kpoint.courseId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.courseId
     *
     * @param courseid the value for kpoint.courseId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.name
     *
     * @return the value of kpoint.name
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.name
     *
     * @param name the value for kpoint.name
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.addTime
     *
     * @return the value of kpoint.addTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.addTime
     *
     * @param addtime the value for kpoint.addTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.playCount
     *
     * @return the value of kpoint.playCount
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getPlaycount() {
        return playcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.playCount
     *
     * @param playcount the value for kpoint.playCount
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setPlaycount(Integer playcount) {
        this.playcount = playcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.videoUrl
     *
     * @return the value of kpoint.videoUrl
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.videoUrl
     *
     * @param videourl the value for kpoint.videoUrl
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl == null ? null : videourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.teachearId
     *
     * @return the value of kpoint.teachearId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Integer getTeachearid() {
        return teachearid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.teachearId
     *
     * @param teachearid the value for kpoint.teachearId
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setTeachearid(Integer teachearid) {
        this.teachearid = teachearid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.playTime
     *
     * @return the value of kpoint.playTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public Date getPlaytime() {
        return playtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.playTime
     *
     * @param playtime the value for kpoint.playTime
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setPlaytime(Date playtime) {
        this.playtime = playtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpoint.countent
     *
     * @return the value of kpoint.countent
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public String getCountent() {
        return countent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpoint.countent
     *
     * @param countent the value for kpoint.countent
     *
     * @mbg.generated Mon Oct 28 13:37:55 CST 2019
     */
    public void setCountent(String countent) {
        this.countent = countent == null ? null : countent.trim();
    }
}